name: Measure coverage

on:
  pull_request:
      branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'

      - name: chmod gralde
        run: chmod +x gradlew

      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew build sonarqube --info

#      - name: Run Coverage
#        run:
#          ./gradlew clean testAndGenerateReport

#      - name: Add coverage to PR
#        if: always()
#        id: jacoco
#        uses: madrapps/jacoco-report@v1.7.1
#        with:
#          title: Test Coverage Report
#          paths: ${{ github.workspace }}/build/reports/jacoco/index.xml
#          token: ${{ secrets.GITHUB_TOKEN }}
#          min-coverage-overall: 50
#          min-coverage-changed-files: 50
#          update-comment: true
#
#      - name: Upload jacoco HTML report
#        uses: actions/upload-artifact@v4
#        with:
#          name: jacoco-html-report
#          path: ${{ github.workspace }}/build/reports/jacoco/index.html

      - name: pull-request-test-success-slack-notice
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_GIT_WEBHOOK_URL}}
        if: success()

      - name: pull-request-test-failure-slack-notice
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_GIT_WEBHOOK_URL}}
        if: failure()